name: Trigger auto deployment for oatconf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/oatconf-AutoDeployTrigger-bbe0a634-b5af-496e-a6cc-4ea70da42805.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.OATCONF_REGISTRY_USERNAME }}
          password: ${{ secrets.OATCONF_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: openastrotech/config-server:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OATCONF_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            CONTAINER_APP_IDS=$(az resource list --tag stage=dev --tag image=openastrotech/config-server --query "[*].id | join(' ', @)" | sed 's|"||g')
            for app_id in ${CONTAINER_APP_IDS}; do
                echo "Updating $app_id"
                az containerapp update --ids "$app_id" --image openastrotech/config-server:${{ github.sha }}
            done
